# Generated by Django 5.1.7 on 2025-03-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_custom_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_field',
        ),
    ]
