# Generated by Django 5.1.7 on 2025-03-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_my_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
